<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Brand;
use App\Models\Product;
use App\Models\Note;
use App\Models\Accord;
use Illuminate\Support\Str;

class ParfumDatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // ═══════════════════════════════════
        // BRANDS
        // ═══════════════════════════════════
        $brandsData = [
            ['name' => 'Mykonos',         'slug' => 'mykonos',         'country' => 'Indonesia', 'description' => 'Brand parfum lokal Indonesia yang viral karena aromanya memiliki ketahanan lama setingkat Extrait de Parfum.'],
            ['name' => 'Velixir Parfum',  'slug' => 'velixir-parfum',  'country' => 'Indonesia', 'description' => 'Brand parfum premium lokal dengan koleksi eksklusif dan aroma berkelas.'],
            ['name' => 'HMNS Parfum',     'slug' => 'hmns-parfum',     'country' => 'Indonesia', 'description' => 'He/Him, Not Specified — brand parfum unisex lokal Indonesia dengan konsep modern.'],
            ['name' => 'SAFF & Co',       'slug' => 'saff-co',         'country' => 'Indonesia', 'description' => 'Brand parfum premium dengan inspirasi dari bahan-bahan eksotis.'],
            ['name' => 'Mandalika Parfum','slug' => 'mandalika-parfum','country' => 'Indonesia', 'description' => 'Terinspirasi dari keindahan alam Lombok dan Nusa Tenggara Barat.'],
            ['name' => 'Kahf',               'slug' => 'kahf',               'country' => 'Indonesia', 'description' => 'Brand grooming dan fragrance lokal Indonesia dengan karakter aroma maskulin, fresh, woody, dan aromatic.'],
            ['name' => 'Carl & Claire',      'slug' => 'carl-claire',       'country' => 'Indonesia', 'description' => 'Brand parfum lokal Indonesia dengan koleksi Eau de Parfum yang modern, elegan, dan mudah dipakai sehari-hari.'],
            ['name' => 'Alchemist Fragrance','slug' => 'alchemist-fragrance','country' => 'Indonesia', 'description' => 'Rumah parfum lokal Indonesia dengan konsep scent elixir, menghadirkan aroma niche yang ekspresif dan berkarakter.'],
            ['name' => 'Oullu',              'slug' => 'oullu',             'country' => 'Indonesia', 'description' => 'Brand parfum lokal Indonesia yang dikenal dengan karakter aroma bold, artistik, dan unisex.'],
            ['name' => 'HINT',               'slug' => 'hint',              'country' => 'Indonesia', 'description' => 'Brand parfum lokal Indonesia dengan konsep genderless fragrance dan scent technology yang modern.'],
        ];

        foreach ($brandsData as $b) {
            Brand::updateOrCreate(['slug' => $b['slug']], $b);
        }
        $this->command->info('✅ Brands seeded: ' . count($brandsData));

        // ═══════════════════════════════════
        // PRODUCTS (hanya dari docx resmi)
        // ═══════════════════════════════════
        $productsData = [

            // ── MYKONOS ─────────────────────────────────────────────
            [
                'name'         => 'California',
                'slug'         => 'california-signature',
                'brand'        => 'Mykonos',
                'category'     => 'Extrait De Parfum',
                'collection'   => 'both',
                'gender'       => 'for men',
                'price'        => 299000,
                'volume_ml'    => 50,
                'image'        => 'images/products/california-signature.png',
                'description'  => 'Savoring a boujee, carefree summer vacation in California. Freshness of aromatic citrus and aquatic notes greet your nose on first whiff giving a fresh, crisp beachside atmosphere. As the scent unfolds, a subtle nuance of lavender begins to emerge, adding a touch of sophistication to the fragrance. As time goes by, it keeps radiating summery freshness complimented by a lush sweetness from the scent of juicy lychee margaritas. It creates a seductive and inviting summer impression with an exotic twist. In the base, Teak wood and vetiver beautifully cut through the freshness of California, giving a classic and gentle reminder of old wealth, an incredibly sensual and sophisticated impression.',
                'top_notes'    => ['Mandarin Orange', 'Lemon'],
                'middle_notes' => ['Lychee', 'Rosemary', 'Cardamom', 'Lavender', 'Geranium', 'Aquatic Notes'],
                'base_notes'   => ['Tonka Bean', 'Teak Wood', 'Vetiver'],
                'accords'      => ['Citrus', 'Watery', 'Aromatic'],
            ],
            [
                'name'         => 'Penthouse',
                'slug'         => 'penthouse-myk',
                'brand'        => 'Mykonos',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 299000,
                'volume_ml'    => 50,
                'image'        => 'images/products/dreamscape.png',
                'description'  => 'Penthouse is the scent of a luxurious bath. It\'s clean, soft, and quietly indulgent. It opens with Sparkling Blackcurrant, airy Aldehydes, Mandarin Zest, and a gentle Rose Mist that feels like fresh water hitting your skin. At the heart, Velvety White Florals, White Tea Vapor, and a White Soap Accord build that immaculate, "fresh-from-the-shower" glow, wrapped in the refined warmth of Cashmere Wood and Cedarwood. As it dries down, Tonka Foam, Iso E Super, Amber, Clean Musks, and Cashmeran melt into the skin like the lingering warmth after a long, lush bath.',
                'top_notes'    => ['Sparkling Blackcurrant', 'Aldehydes', 'Mandarin Zest', 'Rose Mist'],
                'middle_notes' => ['White Floral', 'White Tea', 'White Soap', 'Cashmere Wood', 'Cedarwood'],
                'base_notes'   => ['Tonka Bean', 'Amber', 'Musk', 'Cashmeran'],
                'accords'      => ['Floral', 'Musk', 'Wood'],
            ],
            [
                'name'         => 'Dreamscape',
                'slug'         => 'dreamscape',
                'brand'        => 'Mykonos',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 299000,
                'volume_ml'    => 50,
                'image'        => 'images/products/dreamscape.png',
                'description'  => 'Dreamscape is a scent that feels like a dream you don\'t want to wake up from. It starts with a mouthwatering mix of ripe mango, citrus and red berries, juicy, bright, and irresistibly addictive. As it settles, soft jasmine, warm cedarwood, and a hint of sweetness from coumarin begin to shine through. In the end, it dries down to a cozy blend of musk, woods, and amber. Addictive and comforting, Dreamscape leaves a lasting impression, a hypnotic glow that stays with you long after the moment has passed.',
                'top_notes'    => ['Mango', 'Italian Lemon', 'Rhubarb'],
                'middle_notes' => ['Ginger', 'Jasmine', 'Violet', 'Praline', 'Pink Pepper'],
                'base_notes'   => ['Cedar', 'Grey Amber', 'Tonka Bean', 'Moss'],
                'accords'      => ['Fruity', 'Floral', 'Gourmand'],
            ],
            [
                'name'         => 'Royal Ispahan',
                'slug'         => 'royal-ispahan',
                'brand'        => 'Mykonos',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women',
                'price'        => 299000,
                'volume_ml'    => 50,
                'image'        => 'images/products/royal-ispahan.png',
                'description'  => 'Whisked from a fairytale daydream, where rose and raspberry are dusted with magic. A scent spun with softness — fluffy, dreamy, and effortlessly refined. The opening shimmers with the playful brightness of bergamot, wrapped in the tart sweetness of raspberry and the lush juiciness of lychee. Cotton flower brings a fluffy, airy softness — as if the scent is drifting through a dreamy cloud. At its heart, violet petals bloom beside creamy rose milk, unfolding with elegance and quiet charm. As it settles, warm vanilla melts into guaiac wood and golden amber, leaving behind a soft, comforting warmth that wraps like velvet.',
                'top_notes'    => ['Bergamot', 'Raspberry', 'Lychee', 'Cotton Flower'],
                'middle_notes' => ['Violet', 'Rose', 'Soft Wood'],
                'base_notes'   => ['Vanilla', 'Guaiac Wood', 'Amber'],
                'accords'      => ['Floral', 'Fruity', 'Amber'],
            ],
            [
                'name'         => 'Enchanted',
                'slug'         => 'enchanted',
                'brand'        => 'Mykonos',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 299000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Immerse yourself in the most magical blend of fresh florals. A scent that transports you into a fairytale, somewhere in the meadows, where you\'re surrounded by dewy bouquets of roses and peonies. Sparkling notes of bright citrus compliment this scent beautifully, just like the feeling of warm sunlight shining on your face as you lay down on a bed of flowers.',
                'top_notes'    => ['Mandarin Orange'],
                'middle_notes' => ['Peony', 'Rose', 'Violet', 'Peach'],
                'base_notes'   => ['Iris', 'Musk'],
                'accords'      => ['Floral', 'Fruity', 'Musk'],
            ],

            // ── VELIXIR PARFUM ───────────────────────────────────────
            [
                'name'         => 'Adonis',
                'slug'         => 'adonis',
                'brand'        => 'Velixir Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for men',
                'price'        => 445000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Adonis is for the man who exudes effortless masculinity. Sweet yet undeniably bold, it is crafted for nights that captivate and moments that leave an unforgettable impression.',
                'top_notes'    => ['Lavender', 'Bergamot', 'Mint'],
                'middle_notes' => ['Madagascar Vanilla', 'Benzoin'],
                'base_notes'   => ['Amber', 'Tonka Bean', 'Woody Notes'],
                'accords'      => ['Aromatic', 'Amber', 'Wood'],
            ],
            [
                'name'         => 'Apollo',
                'slug'         => 'apollo',
                'brand'        => 'Velixir Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 445000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Radiant and unstoppable — crafted for those who charge forward with joy, spark momentum with every step, and light up the world simply by moving through it.',
                'top_notes'    => ['Green Apple', 'Ginger', 'Bergamot'],
                'middle_notes' => ['Clary Sage', 'Juniper Berries'],
                'base_notes'   => ['Amberwood', 'Tonka Bean', 'Cedar', 'Vetiver'],
                'accords'      => ['Citrus', 'Aromatic', 'Wood'],
            ],
            [
                'name'         => 'Ares',
                'slug'         => 'ares',
                'brand'        => 'Velixir Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 445000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Ares radiates dynamic elegance and unwavering confidence. He thrives in motion, embodying the energy of open skies and sunlight. Sporty yet refined, Ares feels invigorating and powerful, moving with purpose and grace, clean, grounded, and enduring.',
                'top_notes'    => ['Citrus', 'Mandarin Orange', 'Grapefruit'],
                'middle_notes' => ['Cedarwood', 'Sandalwood'],
                'base_notes'   => ['Musk', 'Amber', 'Patchouli'],
                'accords'      => ['Citrus', 'Wood', 'Musk'],
            ],
            [
                'name'         => 'Aphrodite',
                'slug'         => 'aphrodite',
                'brand'        => 'Velixir Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 475000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'WHERE BEAUTY BECOMES IRRESISTIBLE. Softness in motion. Desire in bloom.',
                'top_notes'    => ['Litchi', 'Ginger', 'Bergamot'],
                'middle_notes' => ['Peony', 'Rose', 'Cacao'],
                'base_notes'   => ['Patchouli'],
                'accords'      => ['Floral', 'Fruity', 'Spices'],
            ],
            [
                'name'         => 'Athena',
                'slug'         => 'athena',
                'brand'        => 'Velixir Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 445000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'A TOUCH TO REMEMBER. Soft laughter, gentle embraces — Athena lingers from the skin to the heart.',
                'top_notes'    => ['Litchi', 'Rhubarb', 'Grapefruit'],
                'middle_notes' => ['Bulgarian Rose', 'Freesia', 'Vanilla'],
                'base_notes'   => ['Orris Root', 'Musk', 'Akigalawood', 'Vetiver'],
                'accords'      => ['Floral', 'Fruity', 'Musk'],
            ],

            // ── HMNS PARFUM ──────────────────────────────────────────
            [
                'name'         => 'Alpha',
                'slug'         => 'alpha',
                'brand'        => 'HMNS Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for men',
                'price'        => 320000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Alpha adalah salah satu parfum maskulin pertama HMNS. Nama Alpha terinspirasi dari huruf pertama alfabet, melambangkan awal dari sesuatu yang baru. Bayangin kamu lagi jalan pagi-pagi di hutan, segarnya udara yang penuh aroma kayu dan dedaunan basah, lalu kamu duduk di depan teras rumah kamu sambil menikmati teh hangat.',
                'top_notes'    => ['Citrus', 'Grass'],
                'middle_notes' => ['Cedarwood'],
                'base_notes'   => ['Green Tea'],
                'accords'      => ['Aromatic', 'Green', 'Wood'],
            ],
            [
                'name'         => 'Farhampton',
                'slug'         => 'farhampton',
                'brand'        => 'HMNS Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for men',
                'price'        => 369000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Farhampton adalah teman sejati yang akan menemani setiap langkahmu hingga akhir perjalanan. Dengan konsentrasi wewangian murni yang tinggi, parfum ini seperti ungkapan dalam menemukan soulmate. Setiap semprotan Farhampton membawamu ke suasana bahagia dan menyenangkan.',
                'top_notes'    => ['Bergamot', 'Ripe Fruit'],
                'middle_notes' => ['Lavender', 'Orange Blossom'],
                'base_notes'   => ['Labdanum', 'Cedarwood', 'Tonka Bean'],
                'accords'      => ['Aromatic', 'Floral', 'Wood'],
            ],
            [
                'name'         => 'Untitled Humans Aroma 01',
                'slug'         => 'untitled-humans-aroma-01',
                'brand'        => 'HMNS Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for men',
                'price'        => 395000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Dalam kolaborasi eksklusif antara HMNS dan Maliq & D\'Essentials, kita mengajak kamu untuk merayakan keunikan kamu tanpa label. Kita paham kalau manusia adalah makhluk yang kompleks, dan wewangian ini merupakan bentuk dari kebebasan ekspresi diri.',
                'top_notes'    => ['Coriander', 'Violet Leaves', 'Ambrette'],
                'middle_notes' => ['Rose Absolute', 'Velvet Note'],
                'base_notes'   => ['Sandalwood', 'Cypriol', 'Vanilla'],
                'accords'      => ['Floral', 'Wood', 'Musk'],
            ],
            [
                'name'         => 'Philea',
                'slug'         => 'philea',
                'brand'        => 'HMNS Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women',
                'price'        => 385000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Bersama Tsana, kita menemukan bunga Mimosa. Ia menjelma menjadi sosok peri yang merayakanmu bersemi dengan bungamu sendiri. Dengan wangi Magnolia, Mimosa dan Cashmeran yang kuat tapi lembut.',
                'top_notes'    => ['Bergamot', 'Magnolia', 'Coriander Seed'],
                'middle_notes' => ['Jasmine', 'Mimosa', 'Orange Blossom'],
                'base_notes'   => ['Cashmeran', 'Heliotrope', 'Musk'],
                'accords'      => ['Floral', 'Musk', 'Citrus'],
            ],
            [
                'name'         => 'SORE Eterna',
                'slug'         => 'sore-eterna',
                'brand'        => 'HMNS Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women',
                'price'        => 385000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Sebuah karya kolaborasi bersama film Sore: Istri dari Masa Depan. Terinspirasi dari kata Eterna, yang artinya "selamanya". Seperti tokoh Sore yang selalu mencintai Jonathan, lagi dan lagi, sampai selamanya.',
                'top_notes'    => ['Bergamot', 'Orange', 'Petit Grain'],
                'middle_notes' => ['Ylang Ylang', 'Rose', 'Peach'],
                'base_notes'   => ['Cedarwood', 'Musk', 'Sandalwood'],
                'accords'      => ['Floral', 'Citrus', 'Wood'],
            ],

            // ── SAFF & CO ────────────────────────────────────────────
            [
                'name'         => 'Eulalie',
                'slug'         => 'eulalie',
                'brand'        => 'SAFF & Co',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 249000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'EULALIE honors the rediscovery of shared affection as an act of hope, embracing life with an open heart. Vivid hues of lychee unfold and entwine with sampaguita, unfurling like an aurora, while a quiet trail of musk whispers that what is true never withers, even in its softest return.',
                'top_notes'    => ['Lychee', 'Raspberry', 'Petalia'],
                'middle_notes' => ['Sampaguita', 'Rose', 'Akigalawood'],
                'base_notes'   => ['Amberwood', 'Musk', 'Cashmeran'],
                'accords'      => ['Floral', 'Fruity', 'Musk'],
            ],
            [
                'name'         => 'Kie Raha',
                'slug'         => 'kie-raha',
                'brand'        => 'SAFF & Co',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 249000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'KIE RAHA sends an ode to the land that raised you. Here, cajuput holds the comfort of a safe embrace. Aquamare flows with clean, watery light, softened by a mineral touch that stirs quiet memories, while Sulawesi patchouli roots the warmth of generations in the first home that shaped you.',
                'top_notes'    => ['Cajuput', 'Yuzu', 'Bigarade'],
                'middle_notes' => ['Aquamare', 'Orchid', 'Crystal Amber'],
                'base_notes'   => ['Sulawesi Patchouli', 'Red Cedar', 'Sandalwood'],
                'accords'      => ['Watery', 'Wood', 'Aromatic'],
            ],
            [
                'name'         => 'Rae Nira',
                'slug'         => 'rae-nira',
                'brand'        => 'SAFF & Co',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 249000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'RAE NIRA holds a trace of moments that feels warm and familiar. Cajuput carries the comforting touch of days you remembered, blending into sweet immortelle that lingers soft as a lullaby, before tolu balsam settles in: amber and unending.',
                'top_notes'    => ['Cajuput', 'Bigarade', 'Lavender'],
                'middle_notes' => ['Jasmine', 'Calypsone', 'Immortelle'],
                'base_notes'   => ['Tolu Balsam', 'Golden Amber', 'Cashmere'],
                'accords'      => ['Floral', 'Amber', 'Aromatic'],
            ],
            [
                'name'         => 'Irai Leima',
                'slug'         => 'irai-leima',
                'brand'        => 'SAFF & Co',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 249000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'In the heart of an ethereal seascape, Irai Leima graces the ancient waters, enchanting the undersea with her divine presence and enigmatic allure. This is an aquatic ode to the goddess of the sea — a luminous mirage that shimmers on the sea line.',
                'top_notes'    => ['Cassis Bud', 'Pink Pepper', 'Peppercorn'],
                'middle_notes' => ['Peony', 'Water Iris', 'Raat Ki Rani'],
                'base_notes'   => ['Ambrette', 'Amber'],
                'accords'      => ['Watery', 'Floral', 'Spices'],
            ],
            [
                'name'         => 'Solaris',
                'slug'         => 'solaris',
                'brand'        => 'SAFF & Co',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 239000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'A seductive vapor that captures your wildest dreams. SOLARIS ignites the fire that lives within you. Bold with a dark twist, SOLARIS is intensely alluring and irresistibly addictive. SOLARIS teaches you the ways of the sun, it does not resist, it simply shines.',
                'top_notes'    => ['Bergamot', 'Mandarin Orange', 'Violet Leaves'],
                'middle_notes' => ['Orris', 'Freesia', 'Cedarwood'],
                'base_notes'   => ['Vetiver', 'Amber', 'Tonka Bean'],
                'accords'      => ['Citrus', 'Floral', 'Wood'],
            ],

            // ── MANDALIKA PARFUM ─────────────────────────────────────
            [
                'name'         => 'No 1',
                'slug'         => 'no-1',
                'brand'        => 'Mandalika Parfum',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 766992,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Embrace an exclusive scent with a metropolitan touch and true luxury with NO1, a captivating and enticing fragrance.',
                'top_notes'    => ['Bergamot', 'Ginger'],
                'middle_notes' => ['Sage', 'Violet'],
                'base_notes'   => ['Amber', 'Cedarwood', 'Musk'],
                'accords'      => ['Aromatic', 'Wood', 'Amber'],
            ],
            [
                'name'         => 'Only The Brave',
                'slug'         => 'only-the-brave',
                'brand'        => 'Mandalika Parfum',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for men',
                'price'        => 766992,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Show your true courage with Only The Brave, a captivating fragrance masterpiece that embodies masculine strength.',
                'top_notes'    => ['Tobacco', 'Vanilla'],
                'middle_notes' => ['Cedarwood', 'Sandalwood'],
                'base_notes'   => ['Musk', 'Vanilla'],
                'accords'      => ['Wood', 'Gourmand', 'Musk'],
            ],
            [
                'name'         => '24 Hours',
                'slug'         => '24-hours',
                'brand'        => 'Mandalika Parfum',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for men',
                'price'        => 889695,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Enjoy a captivating scent all day long with 24 Hours, designed for active and confident men.',
                'top_notes'    => ['Cardamom', 'Lemon', 'Pear'],
                'middle_notes' => ['Cinnamon', 'Iris', 'Lavender'],
                'base_notes'   => ['Amber', 'Cedarwood', 'Vanilla'],
                'accords'      => ['Spices', 'Wood', 'Amber'],
            ],
            [
                'name'         => 'Gorgeous Tuberose',
                'slug'         => 'gorgeous-tuberose',
                'brand'        => 'Mandalika Parfum',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 666022,
                'volume_ml'    => 110,
                'image'        => null,
                'description'  => 'Radiate stunning beauty with Gorgeous Tuberose, a fragrance that creates an unforgettable aura of elegance.',
                'top_notes'    => ['Bergamot', 'Mandarin Orange', 'Red Berries'],
                'middle_notes' => ['Jasmine', 'Orange Blossom', 'Tuberose'],
                'base_notes'   => ['Amber', 'Cedarwood', 'Vanilla'],
                'accords'      => ['Floral', 'Citrus', 'Amber'],
            ],
            [
                'name'         => 'Holy Sweet',
                'slug'         => 'holy-sweet',
                'brand'        => 'Mandalika Parfum',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 889665,
                'volume_ml'    => 110,
                'image'        => null,
                'description'  => 'Embrace a veil of sweet, captivating elegance with Holy Sweet, a fragrance that celebrates softness and beauty.',
                'top_notes'    => ['Cherry', 'Raspberry', 'Strawberry'],
                'middle_notes' => ['Jasmine', 'Violet'],
                'base_notes'   => ['Amber', 'Musk', 'Vanilla'],
                'accords'      => ['Fruity', 'Floral', 'Gourmand'],
            ],

            // ── TAMBAHAN MYKONOS ─────────────────────────────────────
            [
                'name'         => 'Hawaiian Crush',
                'slug'         => 'hawaiian-crush',
                'brand'        => 'Mykonos',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 239000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Parfum tropis fruity-floral yang terasa ceria, manis, dan menyegarkan seperti liburan di pantai.',
                'top_notes'    => ['Lychee', 'Red Fruits', 'Black Tea'],
                'middle_notes' => ['Rose', 'Lily of the Valley', 'Lychee', 'Black Tea'],
                'base_notes'   => ['Amber', 'Patchouli', 'Musk', 'Incense'],
                'accords'      => ['Fruity', 'Floral', 'Amber'],
            ],
            [
                'name'         => 'Inception',
                'slug'         => 'inception-mykonos',
                'brand'        => 'Mykonos',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 299000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Aroma citrus aquatic modern dengan kesan bersih, energik, dan cocok untuk aktivitas harian.',
                'top_notes'    => ['Grapefruit', 'Bergamot', 'Mandarin Orange'],
                'middle_notes' => ['Neroli', 'Ginger', 'Water Notes'],
                'base_notes'   => ['Amberwood', 'Musk', 'Cedarwood'],
                'accords'      => ['Citrus', 'Watery', 'Aromatic'],
            ],
            [
                'name'         => 'Slow Living',
                'slug'         => 'slow-living',
                'brand'        => 'Mykonos',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 299000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Wewangian green-tea musky yang lembut, menenangkan, dan terasa minimalis untuk suasana santai.',
                'top_notes'    => ['Green Tea', 'Bergamot', 'Pear'],
                'middle_notes' => ['Lavender', 'White Floral', 'Sage'],
                'base_notes'   => ['Musk', 'Cedarwood', 'Amber'],
                'accords'      => ['Green', 'Musk', 'Wood'],
            ],
            [
                'name'         => 'Glitch',
                'slug'         => 'glitch-mykonos',
                'brand'        => 'Mykonos',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'sport',
                'gender'       => 'for women and men',
                'price'        => 299000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Parfum fresh-modern dengan nuansa fizzy citrus, powdery, dan watery yang terasa futuristik.',
                'top_notes'    => ['Fizzy Grapefruit', 'Bergamot', 'Magnolia'],
                'middle_notes' => ['Ginger', 'Powdery Notes', 'Water Notes'],
                'base_notes'   => ['Amber', 'Musk', 'Synthetic Notes'],
                'accords'      => ['Synthetic', 'Citrus', 'Watery'],
            ],
            [
                'name'         => 'Milk Drops',
                'slug'         => 'milk-drops',
                'brand'        => 'Mykonos',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 299000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Gourmand creamy yang lembut dan manis, memadukan kesan susu, vanilla, dan musk yang cozy.',
                'top_notes'    => ['Milk Accord', 'Sugar', 'Almond'],
                'middle_notes' => ['Vanilla', 'Cream', 'White Floral'],
                'base_notes'   => ['Musk', 'Tonka Bean', 'Sandalwood'],
                'accords'      => ['Gourmand', 'Vanilla', 'Musk'],
            ],

            // ── TAMBAHAN VELIXIR PARFUM ─────────────────────────────────────
            [
                'name'         => 'Icarus',
                'slug'         => 'icarus',
                'brand'        => 'Velixir Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 445000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Aroma aromatic woody yang ringan namun berani, cocok untuk karakter optimis dan dinamis.',
                'top_notes'    => ['Bergamot', 'Pink Pepper', 'Coconut Water'],
                'middle_notes' => ['Lavender', 'Jasmine', 'Cedarwood'],
                'base_notes'   => ['Amberwood', 'Musk', 'Vetiver'],
                'accords'      => ['Aromatic', 'Wood', 'Musk'],
            ],
            [
                'name'         => 'Hera',
                'slug'         => 'hera',
                'brand'        => 'Velixir Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 445000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Floral fruity yang elegan dengan sentuhan vanilla dan sandalwood, memberi kesan anggun dan lembut.',
                'top_notes'    => ['Pear', 'Mandarin Orange', 'Blackcurrant'],
                'middle_notes' => ['Jasmine', 'Rose', 'Peony'],
                'base_notes'   => ['Vanilla', 'Musk', 'Sandalwood'],
                'accords'      => ['Floral', 'Fruity', 'Musk'],
            ],
            [
                'name'         => 'Morpheus',
                'slug'         => 'morpheus',
                'brand'        => 'Velixir Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 475000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Gourmand amber yang gelap dan adiktif, dibangun dari kopi, cacao, tonka, dan vanilla.',
                'top_notes'    => ['Coffee', 'Bergamot', 'Rum'],
                'middle_notes' => ['Cacao', 'Tonka Bean', 'Cinnamon'],
                'base_notes'   => ['Vanilla', 'Amber', 'Patchouli'],
                'accords'      => ['Gourmand', 'Amber', 'Spices'],
            ],
            [
                'name'         => 'Persephone',
                'slug'         => 'persephone',
                'brand'        => 'Velixir Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 475000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Komposisi fruity floral yang sensual, lembut, dan powdery dengan drydown musky amber.',
                'top_notes'    => ['Pomegranate', 'Litchi', 'Pink Pepper'],
                'middle_notes' => ['Rose', 'Peony', 'Iris'],
                'base_notes'   => ['Musk', 'Amber', 'Cashmeran'],
                'accords'      => ['Fruity', 'Floral', 'Musk'],
            ],
            [
                'name'         => 'Poseidon',
                'slug'         => 'poseidon',
                'brand'        => 'Velixir Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'sport',
                'gender'       => 'for women and men',
                'price'        => 445000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Parfum marine aromatic yang segar seperti udara laut, ditutup dengan cedarwood dan musk.',
                'top_notes'    => ['Sea Salt', 'Lemon', 'Grapefruit'],
                'middle_notes' => ['Marine Notes', 'Lavender', 'Geranium'],
                'base_notes'   => ['Ambergris', 'Cedarwood', 'Musk'],
                'accords'      => ['Watery', 'Citrus', 'Aromatic'],
            ],

            // ── TAMBAHAN HMNS PARFUM ─────────────────────────────────────
            [
                'name'         => 'ORGSM',
                'slug'         => 'orgsm',
                'brand'        => 'HMNS Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 323000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Floral oriental yang manis, ambery, dan memikat untuk memberi kesan percaya diri.',
                'top_notes'    => ['Apple', 'Red Fruits', 'Pink Pepper'],
                'middle_notes' => ['Rose', 'Jasmine', 'Praline'],
                'base_notes'   => ['Vanilla', 'Amber', 'Musk'],
                'accords'      => ['Floral', 'Gourmand', 'Amber'],
            ],
            [
                'name'         => 'Unrosed',
                'slug'         => 'unrosed',
                'brand'        => 'HMNS Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 374000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Interpretasi modern aroma rose yang floral, earthy, dan musky dengan karakter elegan.',
                'top_notes'    => ['Floral Rose Accord'],
                'middle_notes' => ['Earthy Accents', 'Palmarosa'],
                'base_notes'   => ['Musky Undertones', 'Musk'],
                'accords'      => ['Floral', 'Green', 'Musk'],
            ],
            [
                'name'         => 'Essence of The Sun',
                'slug'         => 'essence-of-the-sun',
                'brand'        => 'HMNS Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 369000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Aroma solar floral yang hangat dan bercahaya, terasa segar di awal lalu lembut di drydown.',
                'top_notes'    => ['Bergamot', 'Coriander Seed', 'Pink Pepper'],
                'middle_notes' => ['Jasmine Sambac', 'Turkish Rose', 'Tiare Flower', 'Solar Accord'],
                'base_notes'   => ['Amber', 'Musk', 'Vanilla'],
                'accords'      => ['Citrus', 'Floral', 'Amber'],
            ],
            [
                'name'         => 'Addict',
                'slug'         => 'addict',
                'brand'        => 'HMNS Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 369000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Gourmand floral yang creamy dan modern dengan sentuhan coffee, almond, cacao, dan vanilla.',
                'top_notes'    => ['Lemon', 'Coffee', 'Almond'],
                'middle_notes' => ['Jasmine', 'Tuberose', 'Cacao'],
                'base_notes'   => ['Vanilla', 'Tonka Bean', 'Musk'],
                'accords'      => ['Gourmand', 'Floral', 'Musk'],
            ],
            [
                'name'         => 'Untitled Humans Aroma 02',
                'slug'         => 'untitled-humans-aroma-02',
                'brand'        => 'HMNS Parfum',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 385000,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Wewangian woody green yang bersih, tenang, dan kontemporer untuk gaya unisex.',
                'top_notes'    => ['Bergamot', 'Green Apple', 'Cardamom'],
                'middle_notes' => ['Tea', 'Violet', 'Cedarwood'],
                'base_notes'   => ['Musk', 'Amber', 'Sandalwood'],
                'accords'      => ['Green', 'Wood', 'Musk'],
            ],

            // ── TAMBAHAN SAFF & CO ─────────────────────────────────────
            [
                'name'         => 'SAFF',
                'slug'         => 'saff',
                'brand'        => 'SAFF & Co',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 257900,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Leather fragrance dengan karakter smoky, musky, dan citrus-spicy yang kuat.',
                'top_notes'    => ['Bergamot', 'Mandarin Orange', 'Saffron'],
                'middle_notes' => ['Ylang-ylang', 'Muguet', 'Jasmine'],
                'base_notes'   => ['Dry Amber', 'Leather', 'Musk'],
                'accords'      => ['Leather', 'Amber', 'Musk'],
            ],
            [
                'name'         => 'Ostara',
                'slug'         => 'ostara',
                'brand'        => 'SAFF & Co',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women',
                'price'        => 249000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Amber fruity yang playful dan feminin, dibuka dengan buah segar lalu menghangat di base.',
                'top_notes'    => ['Passion Fruit', 'Pear', 'Raspberry'],
                'middle_notes' => ['Blackcurrant Bud', 'Lily of the Valley'],
                'base_notes'   => ['Patchouli', 'Amber', 'Heliotrope'],
                'accords'      => ['Fruity', 'Floral', 'Amber'],
            ],
            [
                'name'         => 'Las Pozas',
                'slug'         => 'las-pozas',
                'brand'        => 'SAFF & Co',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 249000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Aroma green musky woody yang dewasa, halus, dan cocok untuk formal maupun harian.',
                'top_notes'    => ['Citrus Fresh', 'Pear', 'Green Notes'],
                'middle_notes' => ['Rose', 'Orange Blossom', 'Freesia'],
                'base_notes'   => ['Patchouli', 'Musk', 'Amber'],
                'accords'      => ['Green', 'Musk', 'Wood'],
            ],
            [
                'name'         => 'Xocolatl',
                'slug'         => 'xocolatl',
                'brand'        => 'SAFF & Co',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 249000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Gourmand cacao dengan rasa hangat, manis, dan spicy yang terasa mewah.',
                'top_notes'    => ['Dark Chocolate', 'Orange', 'Cinnamon'],
                'middle_notes' => ['Cacao', 'Coffee', 'Jasmine'],
                'base_notes'   => ['Vanilla', 'Amber', 'Patchouli'],
                'accords'      => ['Gourmand', 'Spices', 'Amber'],
            ],
            [
                'name'         => 'S.O.T.B',
                'slug'         => 'sotb',
                'brand'        => 'SAFF & Co',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 249000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Floral fresh yang ringan dan bersih dengan nuansa beachy, musky, dan ambergris.',
                'top_notes'    => ['Saffron', 'Orange Blossom', 'Bergamot'],
                'middle_notes' => ['Jasmine', 'Violet', 'Lily of the Valley'],
                'base_notes'   => ['Oakmoss', 'Ambergris', 'Musk'],
                'accords'      => ['Floral', 'Musk', 'Watery'],
            ],

            // ── TAMBAHAN MANDALIKA PARFUM ─────────────────────────────────────
            [
                'name'         => 'Remember Me',
                'slug'         => 'remember-me',
                'brand'        => 'Mandalika Parfum',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 766992,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Aroma floral fruity musky yang lembut dan memorable untuk kesan feminin yang bersih.',
                'top_notes'    => ['Pear', 'Raspberry', 'Bergamot'],
                'middle_notes' => ['Rose', 'Jasmine', 'Peony'],
                'base_notes'   => ['Musk', 'Amber', 'Vanilla'],
                'accords'      => ['Floral', 'Fruity', 'Musk'],
            ],
            [
                'name'         => 'Seduction',
                'slug'         => 'seduction-mandalika',
                'brand'        => 'Mandalika Parfum',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women',
                'price'        => 889665,
                'volume_ml'    => 110,
                'image'        => null,
                'description'  => 'Parfum floral gourmand spicy dengan karakter manis, sensual, dan elegan untuk malam hari.',
                'top_notes'    => ['Pink Pepper', 'Cherry', 'Mandarin Orange'],
                'middle_notes' => ['Jasmine', 'Tuberose', 'Cinnamon'],
                'base_notes'   => ['Vanilla', 'Amber', 'Tonka Bean'],
                'accords'      => ['Floral', 'Gourmand', 'Spices'],
            ],
            [
                'name'         => 'The Only One',
                'slug'         => 'the-only-one-mandalika',
                'brand'        => 'Mandalika Parfum',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 766992,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Floral fruity woody yang anggun dengan pembuka segar dan drydown kayu lembut.',
                'top_notes'    => ['Peach', 'Bergamot', 'Mandarin Orange'],
                'middle_notes' => ['Rose', 'Orange Blossom', 'Jasmine'],
                'base_notes'   => ['Cedarwood', 'Sandalwood', 'Musk'],
                'accords'      => ['Floral', 'Fruity', 'Wood'],
            ],
            [
                'name'         => 'Hypnotized',
                'slug'         => 'hypnotized',
                'brand'        => 'Mandalika Parfum',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for men',
                'price'        => 889695,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Amber gourmand maskulin dengan nuansa vanilla, tonka, dan woody yang tebal.',
                'top_notes'    => ['Rum', 'Apple', 'Cardamom'],
                'middle_notes' => ['Cinnamon', 'Lavender', 'Tonka Bean'],
                'base_notes'   => ['Amber', 'Vanilla', 'Woody Notes'],
                'accords'      => ['Amber', 'Gourmand', 'Wood'],
            ],
            [
                'name'         => 'Mr Fantastic',
                'slug'         => 'mr-fantastic',
                'brand'        => 'Mandalika Parfum',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'day',
                'gender'       => 'for men',
                'price'        => 766992,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Aroma fresh fruity spicy yang percaya diri, cocok untuk aktivitas siang dan semi formal.',
                'top_notes'    => ['Bergamot', 'Pineapple', 'Pink Pepper'],
                'middle_notes' => ['Lavender', 'Geranium', 'Nutmeg'],
                'base_notes'   => ['Amber', 'Musk', 'Cedarwood'],
                'accords'      => ['Citrus', 'Fruity', 'Spices'],
            ],

            // ── TAMBAHAN KAHF ─────────────────────────────────────
            [
                'name'         => 'True Brotherhood',
                'slug'         => 'true-brotherhood',
                'brand'        => 'Kahf',
                'category'     => 'Eau de Toilette',
                'collection'   => 'both',
                'gender'       => 'for men',
                'price'        => 82900,
                'volume_ml'    => 35,
                'image'        => null,
                'description'  => 'Aroma hangat spicy dengan cinnamon, tobacco, citrus, dan tonka bean untuk kesan persaudaraan yang elegan.',
                'top_notes'    => ['Cinnamon', 'Citrus', 'Lavender'],
                'middle_notes' => ['Tobacco', 'Incense', 'Geranium'],
                'base_notes'   => ['Tonka Bean', 'Amber', 'Musk'],
                'accords'      => ['Spices', 'Aromatic', 'Amber'],
            ],
            [
                'name'         => 'Revered Oud EDT',
                'slug'         => 'revered-oud-edt',
                'brand'        => 'Kahf',
                'category'     => 'Eau de Toilette',
                'collection'   => 'night',
                'gender'       => 'for men',
                'price'        => 82900,
                'volume_ml'    => 35,
                'image'        => null,
                'description'  => 'Wangi oud, amber, rose, dan vanilla yang hangat, maskulin, dan mudah dipakai.',
                'top_notes'    => ['Rose', 'Lemon', 'Saffron'],
                'middle_notes' => ['Oud', 'Amber', 'Gourmand Notes'],
                'base_notes'   => ['Vanilla', 'Musk', 'Agarwood'],
                'accords'      => ['Oud', 'Amber', 'Gourmand'],
            ],
            [
                'name'         => 'Humbling Forest EDT',
                'slug'         => 'humbling-forest-edt',
                'brand'        => 'Kahf',
                'category'     => 'Eau de Toilette',
                'collection'   => 'day',
                'gender'       => 'for men',
                'price'        => 82900,
                'volume_ml'    => 35,
                'image'        => null,
                'description'  => 'Aroma forest woody yang menyegarkan dengan cypress, rosemary, grapefruit, dan cedarwood.',
                'top_notes'    => ['Cypress', 'Rosemary', 'Grapefruit'],
                'middle_notes' => ['Cedarwood', 'Jasmine', 'Green Notes'],
                'base_notes'   => ['Patchouli', 'Sandalwood', 'Musk'],
                'accords'      => ['Green', 'Wood', 'Aromatic'],
            ],
            [
                'name'         => 'Invigorating Waterfall EDT',
                'slug'         => 'invigorating-waterfall-edt',
                'brand'        => 'Kahf',
                'category'     => 'Eau de Toilette',
                'collection'   => 'sport',
                'gender'       => 'for men',
                'price'        => 82900,
                'volume_ml'    => 35,
                'image'        => null,
                'description'  => 'Fresh aquatic scent dengan lemon, violet, dan cedarwood yang terasa dingin dan energik.',
                'top_notes'    => ['Lemon', 'Marine Notes', 'Mint'],
                'middle_notes' => ['Violet', 'Lavender', 'Water Notes'],
                'base_notes'   => ['Cedarwood', 'Musk', 'Amber'],
                'accords'      => ['Watery', 'Citrus', 'Aromatic'],
            ],
            [
                'name'         => 'Saffron Oud EDP',
                'slug'         => 'saffron-oud-edp',
                'brand'        => 'Kahf',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for men',
                'price'        => 281300,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Oud spicy yang lebih intens dengan saffron, amber, vanilla, dan fruity touch.',
                'top_notes'    => ['Saffron', 'Bergamot', 'Fruity Notes'],
                'middle_notes' => ['Oud', 'Rose', 'Amber'],
                'base_notes'   => ['Vanilla', 'Musk', 'Sandalwood'],
                'accords'      => ['Oud', 'Spices', 'Amber'],
            ],
            [
                'name'         => 'Humbling Forest EDP',
                'slug'         => 'humbling-forest-edp',
                'brand'        => 'Kahf',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for men',
                'price'        => 281300,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Versi EDP yang lebih tahan lama dari forest scent, memadukan citrus, woods, jasmine, dan musk.',
                'top_notes'    => ['Cypress', 'Rosemary', 'Grapefruit'],
                'middle_notes' => ['Cedarwood', 'Guaiac Wood', 'Jasmine'],
                'base_notes'   => ['Patchouli', 'Sandalwood', 'Musk'],
                'accords'      => ['Green', 'Wood', 'Musk'],
            ],
            [
                'name'         => 'Invigorating Waterfall EDP',
                'slug'         => 'invigorating-waterfall-edp',
                'brand'        => 'Kahf',
                'category'     => 'Eau de Parfum',
                'collection'   => 'sport',
                'gender'       => 'for men',
                'price'        => 281300,
                'volume_ml'    => 100,
                'image'        => null,
                'description'  => 'Fresh woody aquatic dengan grapefruit, cypress, cedarwood, dan musk untuk aktivitas aktif.',
                'top_notes'    => ['Grapefruit', 'Cypress', 'Lemon'],
                'middle_notes' => ['Rosemary', 'Cedarwood', 'Marine Notes'],
                'base_notes'   => ['Sandalwood', 'Musk', 'Amber'],
                'accords'      => ['Watery', 'Wood', 'Citrus'],
            ],
            [
                'name'         => 'Mineralwave',
                'slug'         => 'mineralwave',
                'brand'        => 'Kahf',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'day',
                'gender'       => 'for men',
                'price'        => 339500,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Citrus woody mineral dengan cardamom, green tea, ambergris, dan sandalwood.',
                'top_notes'    => ['White Bergamot', 'Cardamom', 'Green Tea'],
                'middle_notes' => ['Ambergris', 'Cedarwood', 'Akigalawood'],
                'base_notes'   => ['Sandalwood', 'Musk', 'Mineral Notes'],
                'accords'      => ['Citrus', 'Wood', 'Watery'],
            ],
            [
                'name'         => 'Aquaterrae',
                'slug'         => 'aquaterrae',
                'brand'        => 'Kahf',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'sport',
                'gender'       => 'for men',
                'price'        => 339500,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Spices aquatic yang dibuat untuk passion seekers, segar namun tetap hangat.',
                'top_notes'    => ['Bergamot', 'Cardamom', 'Sea Salt'],
                'middle_notes' => ['Lavender', 'Sage', 'Aquatic Notes'],
                'base_notes'   => ['Ambergris', 'Patchouli', 'Musk'],
                'accords'      => ['Watery', 'Spices', 'Aromatic'],
            ],
            [
                'name'         => 'Silverwood',
                'slug'         => 'silverwood',
                'brand'        => 'Kahf',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for men',
                'price'        => 339500,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Metallic woody scent dengan karakter modern, maskulin, dan clean.',
                'top_notes'    => ['Bergamot', 'Aldehydes', 'Black Pepper'],
                'middle_notes' => ['Iris', 'Cedarwood', 'Violet'],
                'base_notes'   => ['Musk', 'Amberwood', 'Vetiver'],
                'accords'      => ['Synthetic', 'Wood', 'Musk'],
            ],

            // ── TAMBAHAN CARL & CLAIRE ─────────────────────────────────────
            [
                'name'         => 'A Love Like This',
                'slug'         => 'a-love-like-this',
                'brand'        => 'Carl & Claire',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 279000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Floral romantic yang lembut dan manis, cocok untuk kesan hangat dan personal.',
                'top_notes'    => ['Bergamot', 'Pear', 'Pink Pepper'],
                'middle_notes' => ['Rose', 'Jasmine', 'Peony'],
                'base_notes'   => ['Musk', 'Amber', 'Vanilla'],
                'accords'      => ['Floral', 'Fruity', 'Musk'],
            ],
            [
                'name'         => 'Black Dahlia',
                'slug'         => 'black-dahlia',
                'brand'        => 'Carl & Claire',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 279000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Gourmand coffee-vanilla yang bold, creamy, dan cocok untuk malam hari.',
                'top_notes'    => ['Coffee', 'Almond', 'Bergamot'],
                'middle_notes' => ['Dahlia', 'Jasmine', 'Cacao'],
                'base_notes'   => ['Vanilla', 'Tonka Bean', 'Amber'],
                'accords'      => ['Gourmand', 'Amber', 'Floral'],
            ],
            [
                'name'         => 'Dancing with my Shadow',
                'slug'         => 'dancing-with-my-shadow',
                'brand'        => 'Carl & Claire',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 279000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Amber floral yang misterius dengan sentuhan spicy dan woody.',
                'top_notes'    => ['Saffron', 'Mandarin Orange', 'Pink Pepper'],
                'middle_notes' => ['Jasmine', 'Violet', 'Rose'],
                'base_notes'   => ['Amber', 'Patchouli', 'Sandalwood'],
                'accords'      => ['Amber', 'Floral', 'Spices'],
            ],
            [
                'name'         => 'Delicate Embrace',
                'slug'         => 'delicate-embrace',
                'brand'        => 'Carl & Claire',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women',
                'price'        => 279000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Floral fruity lembut dengan pear, freesia, dan musk yang clean.',
                'top_notes'    => ['Pear', 'Bergamot', 'Litchi'],
                'middle_notes' => ['Freesia', 'Rose', 'Lily of the Valley'],
                'base_notes'   => ['Musk', 'Amber', 'Cedarwood'],
                'accords'      => ['Floral', 'Fruity', 'Musk'],
            ],
            [
                'name'         => 'Emily in Paris - Enchantee',
                'slug'         => 'emily-in-paris-enchantee',
                'brand'        => 'Carl & Claire',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women',
                'price'        => 279000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Floral fruity gourmand yang playful, manis, dan chic.',
                'top_notes'    => ['Raspberry', 'Mandarin Orange', 'Pear'],
                'middle_notes' => ['Rose', 'Jasmine', 'Macaron'],
                'base_notes'   => ['Vanilla', 'Musk', 'Praline'],
                'accords'      => ['Fruity', 'Floral', 'Gourmand'],
            ],
            [
                'name'         => 'Morning Glory',
                'slug'         => 'morning-glory',
                'brand'        => 'Carl & Claire',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 279000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Chypre floral fresh dengan bergamot dan green nuance yang tenang.',
                'top_notes'    => ['Bergamot', 'Lemon', 'Green Notes'],
                'middle_notes' => ['Magnolia', 'Tea', 'Iris'],
                'base_notes'   => ['Moss', 'Amber', 'Musk'],
                'accords'      => ['Citrus', 'Green', 'Floral'],
            ],
            [
                'name'         => 'Song of the Youth',
                'slug'         => 'song-of-the-youth',
                'brand'        => 'Carl & Claire',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 279000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Chypre floral dengan citrus, fruity, iris, vanilla, dan ambery moss.',
                'top_notes'    => ['Citrus', 'Floral Notes', 'Fruity Notes'],
                'middle_notes' => ['Magnolia', 'Musk', 'Iris', 'Vanilla'],
                'base_notes'   => ['Amber', 'Animalic Notes', 'Moss'],
                'accords'      => ['Citrus', 'Floral', 'Musk'],
            ],
            [
                'name'         => 'Spring Sonata',
                'slug'         => 'spring-sonata',
                'brand'        => 'Carl & Claire',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women',
                'price'        => 279000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Floral fruity yang cerah seperti musim semi, lembut dan ceria.',
                'top_notes'    => ['Peach', 'Bergamot', 'Blackcurrant'],
                'middle_notes' => ['Peony', 'Rose', 'Jasmine'],
                'base_notes'   => ['Musk', 'Cedarwood', 'Amber'],
                'accords'      => ['Floral', 'Fruity', 'Musk'],
            ],
            [
                'name'         => 'Take My Hand',
                'slug'         => 'take-my-hand',
                'brand'        => 'Carl & Claire',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 279000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Floral fruity romantis dengan drydown musky yang intimate.',
                'top_notes'    => ['Apple', 'Pear', 'Mandarin Orange'],
                'middle_notes' => ['Rose', 'Freesia', 'Jasmine'],
                'base_notes'   => ['Musk', 'Amber', 'Sandalwood'],
                'accords'      => ['Fruity', 'Floral', 'Musk'],
            ],
            [
                'name'         => 'Talking to the Moon',
                'slug'         => 'talking-to-the-moon',
                'brand'        => 'Carl & Claire',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 279000,
                'volume_ml'    => 30,
                'image'        => null,
                'description'  => 'Floral woody musk dengan nuansa berry yang manis dan dreamy.',
                'top_notes'    => ['Mixed Berries', 'Bergamot', 'Pink Pepper'],
                'middle_notes' => ['Violet', 'Jasmine', 'Rose'],
                'base_notes'   => ['Musk', 'Cedarwood', 'Amber'],
                'accords'      => ['Floral', 'Wood', 'Musk'],
            ],

            // ── TAMBAHAN ALCHEMIST FRAGRANCE ─────────────────────────────────────
            [
                'name'         => 'Home Garden',
                'slug'         => 'home-garden',
                'brand'        => 'Alchemist Fragrance',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 249000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Seek Nature: aroma fruity green yang damai dengan blackberry, grapefruit, clove, cedar, dan vetiver.',
                'top_notes'    => ['Blackberry', 'Grapefruit', 'Clove'],
                'middle_notes' => ['Cedar', 'Vetiver'],
                'base_notes'   => ['Floral Notes', 'Musk'],
                'accords'      => ['Fruity', 'Green', 'Wood'],
            ],
            [
                'name'         => 'Out West',
                'slug'         => 'out-west',
                'brand'        => 'Alchemist Fragrance',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 339000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Fresh woody scent dengan yuzu, bergamot, green apple, rose, plum, musk, patchouli, dan vetiver.',
                'top_notes'    => ['Yuzu', 'Bergamot', 'Green Apple'],
                'middle_notes' => ['Cedarwood', 'Rose', 'Plum'],
                'base_notes'   => ['Musk', 'Patchouli', 'Vetiver'],
                'accords'      => ['Citrus', 'Wood', 'Musk'],
            ],
            [
                'name'         => 'Onirique',
                'slug'         => 'onirique',
                'brand'        => 'Alchemist Fragrance',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women',
                'price'        => 449000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Opulent fruity white floral dengan pear, tuberose, orange blossom, jasmine, dan vanilla.',
                'top_notes'    => ['Pear', 'Orange', 'Clary Sage'],
                'middle_notes' => ['Tuberose', 'Orange Blossom', 'Jasmine'],
                'base_notes'   => ['Vanilla', 'Musk', 'Amber'],
                'accords'      => ['Floral', 'Fruity', 'Amber'],
            ],
            [
                'name'         => 'Galleria',
                'slug'         => 'galleria',
                'brand'        => 'Alchemist Fragrance',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 249000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Sweet floral romantic dengan cape jasmine, plum, tuberose, honey, dan redwood.',
                'top_notes'    => ['Cape Jasmine', 'Plum'],
                'middle_notes' => ['Tuberose', 'Oeillet'],
                'base_notes'   => ['Honey', 'Redwood', 'Musk'],
                'accords'      => ['Floral', 'Fruity', 'Wood'],
            ],
            [
                'name'         => 'Got My Mojo Back',
                'slug'         => 'got-my-mojo-back',
                'brand'        => 'Alchemist Fragrance',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 249000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Gourmand festive dengan chocolate, blackcurrant, almond, tuberose, praline, sandalwood, dan amber.',
                'top_notes'    => ['Chocolate', 'Blackcurrant', 'Almond'],
                'middle_notes' => ['Cedarwood', 'Tuberose', 'Sambac Jasmine'],
                'base_notes'   => ['Praline', 'Sandalwood', 'Amber'],
                'accords'      => ['Gourmand', 'Floral', 'Amber'],
            ],
            [
                'name'         => 'Pink Laundry',
                'slug'         => 'pink-laundry',
                'brand'        => 'Alchemist Fragrance',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 249000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Clean musky floral yang terasa seperti pakaian bersih dengan sentuhan buah pink.',
                'top_notes'    => ['Pink Grapefruit', 'Aldehydes', 'Red Berries'],
                'middle_notes' => ['Rose', 'White Floral', 'Cotton Accord'],
                'base_notes'   => ['Musk', 'Amber', 'Cedarwood'],
                'accords'      => ['Musk', 'Floral', 'Synthetic'],
            ],
            [
                'name'         => 'Powder Room',
                'slug'         => 'powder-room',
                'brand'        => 'Alchemist Fragrance',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women',
                'price'        => 249000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Powdery floral yang soft, elegan, dan intimate dengan iris serta musk.',
                'top_notes'    => ['Bergamot', 'Violet', 'Aldehydes'],
                'middle_notes' => ['Iris', 'Rose', 'Heliotrope'],
                'base_notes'   => ['Musk', 'Vanilla', 'Sandalwood'],
                'accords'      => ['Powdery', 'Floral', 'Musk'],
            ],
            [
                'name'         => 'Forest Rain',
                'slug'         => 'forest-rain',
                'brand'        => 'Alchemist Fragrance',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 249000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Aroma green watery seperti hujan di hutan, segar, earthy, dan menenangkan.',
                'top_notes'    => ['Rain Accord', 'Green Leaves', 'Bergamot'],
                'middle_notes' => ['Cedarwood', 'Vetiver', 'Jasmine'],
                'base_notes'   => ['Moss', 'Patchouli', 'Musk'],
                'accords'      => ['Green', 'Watery', 'Wood'],
            ],
            [
                'name'         => 'Farshore',
                'slug'         => 'farshore',
                'brand'        => 'Alchemist Fragrance',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'sport',
                'gender'       => 'for women and men',
                'price'        => 339000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Marine citrus woody yang menggambarkan udara pantai dan ombak yang bersih.',
                'top_notes'    => ['Sea Salt', 'Bergamot', 'Lemon'],
                'middle_notes' => ['Marine Notes', 'Lavender', 'Sage'],
                'base_notes'   => ['Ambergris', 'Cedarwood', 'Musk'],
                'accords'      => ['Watery', 'Citrus', 'Wood'],
            ],
            [
                'name'         => 'A Night in Marrakesh',
                'slug'         => 'a-night-in-marrakesh',
                'brand'        => 'Alchemist Fragrance',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 449000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Spicy amber oriental yang hangat dengan saffron, rose, incense, dan sandalwood.',
                'top_notes'    => ['Saffron', 'Cardamom', 'Orange'],
                'middle_notes' => ['Rose', 'Incense', 'Jasmine'],
                'base_notes'   => ['Amber', 'Sandalwood', 'Patchouli'],
                'accords'      => ['Spices', 'Amber', 'Wood'],
            ],

            // ── TAMBAHAN OULLU ─────────────────────────────────────
            [
                'name'         => 'Aether',
                'slug'         => 'aether',
                'brand'        => 'Oullu',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 389000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Aroma airy clean yang ringan, musky, dan modern.',
                'top_notes'    => ['Bergamot', 'Aldehydes', 'Pear'],
                'middle_notes' => ['White Tea', 'Lavender', 'Iris'],
                'base_notes'   => ['Musk', 'Amber', 'Cedarwood'],
                'accords'      => ['Musk', 'Synthetic', 'Aromatic'],
            ],
            [
                'name'         => 'Arcana',
                'slug'         => 'arcana',
                'brand'        => 'Oullu',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 389000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Parfum mysterious amber woody dengan sentuhan spicy dan resinous.',
                'top_notes'    => ['Black Pepper', 'Bergamot', 'Saffron'],
                'middle_notes' => ['Incense', 'Rose', 'Cedarwood'],
                'base_notes'   => ['Amber', 'Patchouli', 'Musk'],
                'accords'      => ['Amber', 'Spices', 'Wood'],
            ],
            [
                'name'         => 'Bird Song',
                'slug'         => 'bird-song',
                'brand'        => 'Oullu',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 389000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Floral green yang cerah dan natural seperti pagi hari.',
                'top_notes'    => ['Neroli', 'Bergamot', 'Green Leaves'],
                'middle_notes' => ['Jasmine', 'Lily of the Valley', 'Rose'],
                'base_notes'   => ['Musk', 'Cedarwood', 'Amber'],
                'accords'      => ['Floral', 'Green', 'Musk'],
            ],
            [
                'name'         => 'Deep Dive',
                'slug'         => 'deep-dive',
                'brand'        => 'Oullu',
                'category'     => 'Eau de Parfum',
                'collection'   => 'sport',
                'gender'       => 'for women and men',
                'price'        => 389000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Aquatic aromatic yang dingin, segar, dan cocok untuk cuaca panas.',
                'top_notes'    => ['Sea Salt', 'Grapefruit', 'Mint'],
                'middle_notes' => ['Marine Notes', 'Violet', 'Lavender'],
                'base_notes'   => ['Ambergris', 'Musk', 'Cedarwood'],
                'accords'      => ['Watery', 'Aromatic', 'Citrus'],
            ],
            [
                'name'         => 'Dia',
                'slug'         => 'dia',
                'brand'        => 'Oullu',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women',
                'price'        => 389000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Fruity floral yang terang, lembut, dan feminin.',
                'top_notes'    => ['Mandarin Orange', 'Pear', 'Peach'],
                'middle_notes' => ['Rose', 'Peony', 'Jasmine'],
                'base_notes'   => ['Musk', 'Amber', 'Vanilla'],
                'accords'      => ['Fruity', 'Floral', 'Musk'],
            ],
            [
                'name'         => 'Ego',
                'slug'         => 'ego-oullu',
                'brand'        => 'Oullu',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 389000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Statement scent dengan cassis, fig, violet, geranium, cedar, dan patchouli.',
                'top_notes'    => ['Cassis', 'Fig'],
                'middle_notes' => ['Violet', 'Geranium'],
                'base_notes'   => ['Cedar', 'Patchouli'],
                'accords'      => ['Fruity', 'Floral', 'Wood'],
            ],
            [
                'name'         => 'Phobos',
                'slug'         => 'phobos',
                'brand'        => 'Oullu',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 389000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Dark woody aromatic yang intens dengan nuansa smoky dan earthy.',
                'top_notes'    => ['Bergamot', 'Black Pepper', 'Clove'],
                'middle_notes' => ['Cedarwood', 'Vetiver', 'Incense'],
                'base_notes'   => ['Patchouli', 'Amber', 'Musk'],
                'accords'      => ['Wood', 'Spices', 'Amber'],
            ],
            [
                'name'         => 'Solar Rays',
                'slug'         => 'solar-rays',
                'brand'        => 'Oullu',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 389000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Solar citrus floral yang hangat dan cheerful.',
                'top_notes'    => ['Bergamot', 'Mandarin Orange', 'Orange Blossom'],
                'middle_notes' => ['Tiare Flower', 'Jasmine', 'Ylang-ylang'],
                'base_notes'   => ['Amber', 'Musk', 'Vanilla'],
                'accords'      => ['Citrus', 'Floral', 'Amber'],
            ],
            [
                'name'         => 'Umbra',
                'slug'         => 'umbra',
                'brand'        => 'Oullu',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 389000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Amber musky yang gelap, clean, dan sophisticated.',
                'top_notes'    => ['Cardamom', 'Bergamot', 'Pink Pepper'],
                'middle_notes' => ['Iris', 'Rose', 'Cedarwood'],
                'base_notes'   => ['Amber', 'Musk', 'Sandalwood'],
                'accords'      => ['Amber', 'Musk', 'Wood'],
            ],
            [
                'name'         => 'Zephyr',
                'slug'         => 'zephyr',
                'brand'        => 'Oullu',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 389000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Fresh airy scent dengan citrus, tea, dan musk yang ringan.',
                'top_notes'    => ['Lemon', 'Bergamot', 'Green Tea'],
                'middle_notes' => ['Lavender', 'Violet', 'White Floral'],
                'base_notes'   => ['Musk', 'Amber', 'Cedarwood'],
                'accords'      => ['Citrus', 'Green', 'Musk'],
            ],

            // ── TAMBAHAN HINT ─────────────────────────────────────
            [
                'name'         => 'Cherise',
                'slug'         => 'cherise-hint',
                'brand'        => 'HINT',
                'category'     => 'Extrait de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 399000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Fruity floral cherry scent yang manis, playful, dan bold.',
                'top_notes'    => ['Cherry', 'Raspberry', 'Bergamot'],
                'middle_notes' => ['Rose', 'Jasmine', 'Almond'],
                'base_notes'   => ['Vanilla', 'Amber', 'Musk'],
                'accords'      => ['Fruity', 'Floral', 'Gourmand'],
            ],
            [
                'name'         => 'Dragon',
                'slug'         => 'dragon-hint',
                'brand'        => 'HINT',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 349000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Spicy woody fragrance dengan karakter panas, smoky, dan percaya diri.',
                'top_notes'    => ['Saffron', 'Black Pepper', 'Bergamot'],
                'middle_notes' => ['Incense', 'Leather', 'Rose'],
                'base_notes'   => ['Oud', 'Amber', 'Patchouli'],
                'accords'      => ['Spices', 'Leather', 'Wood'],
            ],
            [
                'name'         => 'Epitome',
                'slug'         => 'epitome-hint',
                'brand'        => 'HINT',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 349000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Clean musky scent yang elegan, minimalis, dan versatile.',
                'top_notes'    => ['Bergamot', 'Aldehydes', 'Pink Pepper'],
                'middle_notes' => ['Iris', 'Violet', 'Tea'],
                'base_notes'   => ['Musk', 'Amber', 'Cedarwood'],
                'accords'      => ['Musk', 'Synthetic', 'Wood'],
            ],
            [
                'name'         => 'Fatale',
                'slug'         => 'fatale-hint',
                'brand'        => 'HINT',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 349000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Amber floral yang sensual dengan buah merah dan vanilla.',
                'top_notes'    => ['Red Berries', 'Pear', 'Pink Pepper'],
                'middle_notes' => ['Jasmine', 'Rose', 'Tuberose'],
                'base_notes'   => ['Vanilla', 'Amber', 'Patchouli'],
                'accords'      => ['Floral', 'Amber', 'Fruity'],
            ],
            [
                'name'         => 'Identity',
                'slug'         => 'identity-hint',
                'brand'        => 'HINT',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 349000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Ozonic aquatic scent dengan lemon, melon, watery accord, geranium, amber, patchouli, dan sandalwood.',
                'top_notes'    => ['Lemon', 'Ozonic Notes', 'Melon'],
                'middle_notes' => ['Watery Notes', 'Geranium', 'Lily of the Valley'],
                'base_notes'   => ['Amber', 'Patchouli', 'Sea Moss', 'Sandalwood'],
                'accords'      => ['Watery', 'Citrus', 'Amber'],
            ],
            [
                'name'         => 'Matcha',
                'slug'         => 'matcha-hint',
                'brand'        => 'HINT',
                'category'     => 'Eau de Parfum',
                'collection'   => 'day',
                'gender'       => 'for women and men',
                'price'        => 349000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Green gourmand dengan nuansa matcha creamy, fresh, dan soft.',
                'top_notes'    => ['Matcha', 'Bergamot', 'Green Tea'],
                'middle_notes' => ['Milk Accord', 'Jasmine', 'Rice Accord'],
                'base_notes'   => ['Vanilla', 'Musk', 'Tonka Bean'],
                'accords'      => ['Green', 'Gourmand', 'Musk'],
            ],
            [
                'name'         => 'Metaverse',
                'slug'         => 'metaverse-hint',
                'brand'        => 'HINT',
                'category'     => 'Eau de Parfum',
                'collection'   => 'sport',
                'gender'       => 'for women and men',
                'price'        => 349000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Futuristic synthetic citrus scent dengan watery dan musk.',
                'top_notes'    => ['Grapefruit', 'Aldehydes', 'Mint'],
                'middle_notes' => ['Water Notes', 'Violet', 'Lavender'],
                'base_notes'   => ['Musk', 'Amberwood', 'Synthetic Notes'],
                'accords'      => ['Synthetic', 'Citrus', 'Watery'],
            ],
            [
                'name'         => 'Noble',
                'slug'         => 'noble-hint',
                'brand'        => 'HINT',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 349000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Woody amber scent yang classy dengan saffron, cedarwood, dan musk.',
                'top_notes'    => ['Saffron', 'Bergamot', 'Cardamom'],
                'middle_notes' => ['Cedarwood', 'Rose', 'Iris'],
                'base_notes'   => ['Amber', 'Musk', 'Sandalwood'],
                'accords'      => ['Wood', 'Amber', 'Musk'],
            ],
            [
                'name'         => 'Realm',
                'slug'         => 'realm-hint',
                'brand'        => 'HINT',
                'category'     => 'Eau de Parfum',
                'collection'   => 'both',
                'gender'       => 'for women and men',
                'price'        => 349000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Warm comforting scent yang ramah, lembut, dan menenangkan.',
                'top_notes'    => ['Bergamot', 'Pear', 'Pink Pepper'],
                'middle_notes' => ['Lavender', 'Jasmine', 'Tea'],
                'base_notes'   => ['Amber', 'Musk', 'Vanilla'],
                'accords'      => ['Aromatic', 'Amber', 'Musk'],
            ],
            [
                'name'         => 'Resurrect',
                'slug'         => 'resurrect-hint',
                'brand'        => 'HINT',
                'category'     => 'Eau de Parfum',
                'collection'   => 'night',
                'gender'       => 'for women and men',
                'price'        => 349000,
                'volume_ml'    => 50,
                'image'        => null,
                'description'  => 'Dark aromatic woody dengan smoky amber dan patchouli.',
                'top_notes'    => ['Black Pepper', 'Lemon', 'Clary Sage'],
                'middle_notes' => ['Incense', 'Cedarwood', 'Geranium'],
                'base_notes'   => ['Patchouli', 'Amber', 'Musk'],
                'accords'      => ['Aromatic', 'Wood', 'Amber'],
            ],
        ];

        // Clear existing products & notes pivot first to avoid duplicates
        Product::whereIn('slug', array_column($productsData, 'slug'))->each(function($p) {
            $p->notes()->detach();
            $p->accords()->detach();
        });

        foreach ($productsData as $data) {
            $brand = Brand::where('slug', Str::slug($data['brand']))->first();
            if (!$brand) {
                $this->command->warn("Brand not found: {$data['brand']}");
                continue;
            }

            $product = Product::updateOrCreate(
                ['slug' => $data['slug']],
                [
                    'name'        => $data['name'],
                    'slug'        => $data['slug'],
                    'brand_id'    => $brand->id,
                    'category'    => $data['category'],
                    'collection'  => $data['collection'],
                    'gender'      => $data['gender'],
                    'price'       => $data['price'],
                    'volume_ml'   => $data['volume_ml'],
                    'image'       => $data['image'],
                    'description' => $data['description'],
                    'is_active'   => true,
                ]
            );

            // Sync notes (detach dulu sudah dilakukan di atas)
            $noteSync = [];
            foreach ($data['top_notes'] as $name) {
                $note = Note::firstOrCreate(
                    ['slug' => Str::slug($name . '-top'), 'type' => 'top'],
                    ['name' => $name, 'slug' => Str::slug($name . '-top'), 'type' => 'top']
                );
                $noteSync[$note->id] = ['note_type' => 'top'];
            }
            foreach ($data['middle_notes'] as $name) {
                $note = Note::firstOrCreate(
                    ['slug' => Str::slug($name . '-middle'), 'type' => 'middle'],
                    ['name' => $name, 'slug' => Str::slug($name . '-middle'), 'type' => 'middle']
                );
                $noteSync[$note->id] = ['note_type' => 'middle'];
            }
            foreach ($data['base_notes'] as $name) {
                $note = Note::firstOrCreate(
                    ['slug' => Str::slug($name . '-base'), 'type' => 'base'],
                    ['name' => $name, 'slug' => Str::slug($name . '-base'), 'type' => 'base']
                );
                $noteSync[$note->id] = ['note_type' => 'base'];
            }
            $product->notes()->sync($noteSync);

            // Sync accords
            $accordIds = [];
            foreach ($data['accords'] as $accordName) {
                $accord = Accord::where('name', $accordName)->first();
                if ($accord) $accordIds[] = $accord->id;
            }
            $product->accords()->sync($accordIds);
        }

        $this->command->info('✅ Products seeded: ' . count($productsData) . ' (dari docx resmi)');
    }
}
